name: website deployment
on: [push]
jobs:  
  deploy:    
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@main
      - name: deploy website to example.com
        uses: appleboy/scp-action@main
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "*"
          target: "/var/www/html/"
          strip_components: 1
